run:
  # Extend default timeout for running in single-core CI
  timeout: 5m
  tests: false
issues:
  exclude-rules:
    - path: pkg/mod
      linters:
        - '*'
linters:
  enable:
    # Default linters plus these:
    - revive
    - gofmt
    - goimports
