/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	"github.com/SAP/sap-btp-service-operator/api"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"reflect"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// SharedServiceInstanceSpec defines the desired state of SharedServiceInstance
type SharedServiceInstanceSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// The k8s name of the service instance to bind, should be in the namespace of the binding
	// +required
	// +kubebuilder:validation:MinLength=1
	ServiceInstanceName string `json:"serviceInstanceName"`
}

// SharedServiceInstanceStatus defines the observed state of SharedServiceInstance
type SharedServiceInstanceStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// The ID of the instance in SM associated with binding
	// +optional
	InstanceID string `json:"instanceID,omitempty"`

	// URL of ongoing operation for the service binding
	OperationURL string `json:"operationURL,omitempty"`

	// Service binding conditions
	Conditions []metav1.Condition `json:"conditions"`

	// Last generation that was acted on
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Indicates whether binding is ready for usage
	Ready metav1.ConditionStatus `json:"ready,omitempty"`

	// Indicates if currently the state of the instance is shared or not
	Shared bool `json:"shared,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:JSONPath=".spec.serviceInstanceName",name="Instance",type=string
// +kubebuilder:printcolumn:JSONPath=".status.conditions[0].reason",name="Status",type=string
// +kubebuilder:printcolumn:JSONPath=".status.ready",name="Ready",type=string
// +kubebuilder:printcolumn:JSONPath=".metadata.creationTimestamp",name="Age",type=date
// +kubebuilder:printcolumn:JSONPath=".status.conditions[0].message",name="Message",type=string,priority=1

// SharedServiceInstance is the Schema for the sharedserviceinstances API
type SharedServiceInstance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SharedServiceInstanceSpec   `json:"spec,omitempty"`
	Status SharedServiceInstanceStatus `json:"status,omitempty"`
}

func (ssi *SharedServiceInstance) ValidateCreate() error {
	return nil
}

func (ssi *SharedServiceInstance) ValidateDelete() error {
	return nil
}

func (in *SharedServiceInstance) GetParameters() *runtime.RawExtension {
	return nil
}

// SharedServiceInstanceList contains a list of SharedServiceInstance
type SharedServiceInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SharedServiceInstance `json:"items"`
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedServiceInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (ssi *SharedServiceInstance) GetConditions() []metav1.Condition {
	return ssi.Status.Conditions
}

func (ssi *SharedServiceInstance) SetConditions(conditions []metav1.Condition) {
	ssi.Status.Conditions = conditions
}

func (ssi *SharedServiceInstance) GetControllerName() api.ControllerName {
	return api.SharedServiceInstanceController
}

func (ssi *SharedServiceInstance) GetStatus() interface{} {
	return ssi.Status
}

func (ssi *SharedServiceInstance) SetStatus(status interface{}) {
	ssi.Status = status.(SharedServiceInstanceStatus)
}

func (ssi *SharedServiceInstance) GetObservedGeneration() int64 {
	return ssi.Status.ObservedGeneration
}

func (ssi *SharedServiceInstance) SetObservedGeneration(newObserved int64) {
	ssi.Status.ObservedGeneration = newObserved
}

func (ssi *SharedServiceInstance) DeepClone() api.SAPBTPResource {
	return ssi.DeepCopy()
}

func (ssi *SharedServiceInstance) GetReady() metav1.ConditionStatus {
	return ssi.Status.Ready
}

func (ssi *SharedServiceInstance) SetReady(ready metav1.ConditionStatus) {
	ssi.Status.Ready = ready
}

func (ssi *SharedServiceInstance) specChanged(old runtime.Object) bool {
	oldSharedServiceInstance := old.(*SharedServiceInstance)
	oldSpec := oldSharedServiceInstance.Spec.DeepCopy()
	newSpec := ssi.Spec.DeepCopy()

	return !reflect.DeepEqual(oldSpec, newSpec)
}

func init() {
	SchemeBuilder.Register(&SharedServiceInstance{}, &SharedServiceInstanceList{})
}
