// Your header goes here...
//

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/SAP/sap-btp-service-operator/api/services.cloud.sap.com/v1alpha1"
	"github.com/SAP/sap-btp-service-operator/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type ServicesV1alpha1Interface interface {
	RESTClient() rest.Interface
	ServiceBindingsGetter
	ServiceInstancesGetter
}

// ServicesV1alpha1Client is used to interact with features provided by the services.cloud.sap.com group.
type ServicesV1alpha1Client struct {
	restClient rest.Interface
}

func (c *ServicesV1alpha1Client) ServiceBindings(namespace string) ServiceBindingInterface {
	return newServiceBindings(c, namespace)
}

func (c *ServicesV1alpha1Client) ServiceInstances(namespace string) ServiceInstanceInterface {
	return newServiceInstances(c, namespace)
}

// NewForConfig creates a new ServicesV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*ServicesV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ServicesV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new ServicesV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ServicesV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ServicesV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *ServicesV1alpha1Client {
	return &ServicesV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ServicesV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
