// Your header goes here...
//

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/SAP/sap-btp-service-operator/client/clientset/versioned/typed/services.cloud.sap.com/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeServicesV1alpha1 struct {
	*testing.Fake
}

func (c *FakeServicesV1alpha1) ServiceBindings(namespace string) v1alpha1.ServiceBindingInterface {
	return &FakeServiceBindings{c, namespace}
}

func (c *FakeServicesV1alpha1) ServiceInstances(namespace string) v1alpha1.ServiceInstanceInterface {
	return &FakeServiceInstances{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeServicesV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
