apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: sample-instance-5
  annotations:
    services.cloud.sap.com/ignoreNonTransientError: "true"
spec:
  serviceOfferingName: led-zeppelin
  servicePlanName: x-small
