apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: privatelink
spec:
  serviceOfferingName: privatelink
  servicePlanName: standard
  parameters:
    serviceName: com.amazonaws.vpce.eu-central-1.vpce-svc-00000000000abcdef
