apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: sample-binding-secret-template
spec:
  serviceInstanceName: sample-instance-1
  secretName: mykey
  secretTemplate: |
    apiVersion: v1
    kind: Secret
    metadata:
      labels:
        instance_plan: {{ .instanceProperties.plan }}
      annotations:
        instance_name: {{ .instanceProperties.instance_name }}
    stringData:
      PASSWORD: {{ .credentialProperties.password }}
      BROKER: {{ .instanceProperties.type }}