apiVersion: v1
kind: Secret
metadata:
  name: <subaccountID>-sap-btp-service-operator
  namespace: sap-btp-operator
type: Opaque
data:
  clientid: ****
  clientsecret: ****
  sm_url: ****
  tokenurl: ****
  tokenurlsuffix: ****