{{- if .Values.manager.certificates.certManager }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sap-btp-operator-selfsigned-issuer
  namespace: {{.Release.Namespace}}
spec:
  selfSigned: {}
{{- end}}