{{- if .Values.manager.certificates.certManager }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sap-btp-operator-serving-cert
  namespace: {{.Release.Namespace}}
spec:
  dnsNames:
    - sap-btp-operator-webhook-service.{{.Release.Namespace}}.svc
    - sap-btp-operator-webhook-service.{{.Release.Namespace}}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: sap-btp-operator-selfsigned-issuer
  secretName: webhook-server-cert
{{- end}}