apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: sap-btp-operator-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        control-plane: controller-manager
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "btp-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kube-rbac-proxy
          securityContext:
            {{- toYaml .Values.proxy.securityContext | nindent 12 }}
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          ports:
            - containerPort: 8443
              name: https
        - name: manager
          securityContext:
            {{- toYaml .Values.manager.securityContext | nindent 12 }}
          args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          command:
            - /manager
          envFrom:
            - configMapRef:
                name: sap-btp-operator-config
          image: "{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              cpu: {{.Values.manager.cpu_limit}}
              memory: {{.Values.manager.memory_limit}}
            requests:
              cpu: {{.Values.manager.req_cpu_limit}}
              memory: {{.Values.manager.req_memory_limit}}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
