{{ if .Values.manager.pullSecretTemplate }}
{{- $auths := dict -}}
{{- range $authentication := .Values.manager.pullSecretTemplate.authentication }}
  {{- $auth := printf "%s:%s" $authentication.username $authentication.password | b64enc }}
  {{- $repoItem := dict }}
  {{- $_ := set $repoItem "auth" $auth }}
  {{- $_ := set $auths $authentication.host $repoItem }}
  {{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.manager.pullSecretTemplate.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" $auths | toJson | b64enc | quote }}
  {{- end }}
