apiVersion: batch/v1
kind: Job
metadata:
  name: pre-delete-job
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  completions: 1
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: sap-btp-operator
      containers:
        - name: pre-delete-operator
          image: "bitnami/kubectl"
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              kubectl get servicebindings.services.cloud.sap.com -A
              timeout 30 kubectl delete servicebindings.services.cloud.sap.com --all --all-namespaces
              if [ $? -eq 124 ]; then
                echo "Failed to deleted service binding"
                exit 1
              else
                echo "All service bindings were deleted successfully"
              fi
              
              kubectl get serviceinstances.services.cloud.sap.com -A              
              timeout 30 kubectl delete serviceinstances.services.cloud.sap.com --all --all-namespaces
              if [ $? -eq 124 ]; then
                echo "Failed to deleted service instance"
                exit 1
              else
                echo "All service instances were deleted successfully"
              fi
      restartPolicy: Never
