apiVersion: batch/v1
kind: Job
metadata:
  name: pre-delete-job
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: sap-btp-operator
      containers:
        - name: pre-delete-operator
          image: "bitnami/kubectl:latest"
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              serviceinstances=$(kubectl get serviceinstances.services.cloud.sap.com -A)
              servicebindings=$(kubectl get servicebindings.services.cloud.sap.com -A)

              echo "deleting the following service bindings: $servicebindings"
              kubectl delete servicebindings.services.cloud.sap.com --all --all-namespaces

              echo "deleting the following service instances: $serviceinstances"
              kubectl delete serviceinstances.services.cloud.sap.com --all --all-namespaces

              echo "All service instances and bindings got deleted"
      restartPolicy: OnFailure
