{{ if .Values.manager.pullSecrets }}
{{- $auths := dict -}}
{{- range $secret := .Values.manager.pullSecrets }}
  {{- $auth := printf "%s:%s" $secret.authentication.username $secret.authentication.password | b64enc }}
  {{- $repoItem := dict }}
  {{- $_ := set $repoItem "auth" $auth }}
  {{- $_ := set $auths $secret.host $repoItem }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.manager.imagePullSecretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" $auths | toJson | b64enc | quote }}
{{- end }}
