{{ if .Values.manager.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sap-btp-service-operator
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.manager.secret.b64encoded }}
  clientid: {{ .Values.manager.secret.clientid | quote }}
  clientsecret: {{ .Values.manager.secret.clientsecret | quote }}
  url: {{ .Values.manager.secret.url | quote }}
  tokenurl: {{ .Values.manager.secret.tokenurl | quote }}
  {{- else}}
  clientid: {{ .Values.manager.secret.clientid | b64enc | quote }}
  clientsecret: {{ .Values.manager.secret.clientsecret | b64enc | quote }}
  url: {{ .Values.manager.secret.url | b64enc | quote }}
  tokenurl: {{ .Values.manager.secret.tokenurl | b64enc | quote }}
  {{- end }}
  tokenurlsuffix: {{ .Values.manager.secret.tokenurlsuffix | b64enc | quote }}
{{ end }}
