apiVersion: v1
kind: Secret
metadata:
  name: sap-btp-service-operator
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.manager.secret.clientid }}
  clientid: {{ .Values.manager.secret.clientid | b64enc | quote }}
  {{- end }}
  {{- if .Values.manager.secret.clientsecret }}
  clientsecret: {{ .Values.manager.secret.clientsecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.manager.secret.url }}
  url: {{ .Values.manager.secret.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.manager.secret.tokenurl }}
  tokenurl: {{ .Values.manager.secret.tokenurl | b64enc | quote }}
  {{- end }}
  tokenurlsuffix: {{ .Values.manager.secret.tokenurlsuffix | b64enc | quote }}
  {{- end }}
