{{- if and (.Values.manager.secret.tls.crt) (.Values.manager.secret.tls.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: sap-btp-service-operator-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.manager.secret.tls.crt | b64enc }}
  tls.key: {{ .Values.manager.secret.tls.key | b64enc }}
{{- end }}
