// Your header goes here...
//

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ServiceBindingListerExpansion allows custom methods to be added to
// ServiceBindingLister.
type ServiceBindingListerExpansion interface{}

// ServiceBindingNamespaceListerExpansion allows custom methods to be added to
// ServiceBindingNamespaceLister.
type ServiceBindingNamespaceListerExpansion interface{}

// ServiceInstanceListerExpansion allows custom methods to be added to
// ServiceInstanceLister.
type ServiceInstanceListerExpansion interface{}

// ServiceInstanceNamespaceListerExpansion allows custom methods to be added to
// ServiceInstanceNamespaceLister.
type ServiceInstanceNamespaceListerExpansion interface{}
